site_name: Welcome to YC365.io
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - search.highlight
    - content.code.copy
plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 简体中文
          build: true
          nav_translations:
            Index: 首页
        - locale: th
          name: ภาษาไทย
          build: true
          nav_translations:
            Index: หน้าหลัก
        - locale: pt
          name: Português
          build: true
          nav_translations:
            Index: Início
nav:
  - Index: index.md
  - Project Whitepaper: project-whitepaper.md
  - Prerequisites: prerequisites.md
  - System Architecture: system-architecture.md
#  - Multi-language Support: multi-language-support.md
  - Business Process Flow: business-process.md
#  - Role Responsibilities: role-responsibilities.md
  - Terms of Use: terms-of-use.md
  - Earn Points: earn-points.md
  - YC365 Faucet: yc365-faucet.md
  - YC365 tBNB Faucet: yc365-tbnb-faucet.md 
  - Get Started:
      - Introduction: get-started.md
      - What is YC365?: what-is-yc365.md
      - How to Deposit: how-to-deposit.md
      - Making Your First Trade: making-your-first-trade.md
  - Deposits and Withdraw:
      - Deposits: deposits.md
      - Withdraw: withdraw.md
  - Markets:
      - How Are Markets Created?: how-are-markets-created.md
      - How Are Prices Calculated?: how-are-prices-calculated.md
      - How Are Prediction Markets Resolved?: how-are-prediction-markets-resolved.md
      - How Are Markets Clarified?: how-are-markets-clarified.md
      - How Are Markets Disputed?: how-are-markets-disputed.md
  - Trading:
      - Overview: trading.md
      - Limit Orders: limit-orders.md
      - Trading Fees: trading-fees.md
      - Using the Order Book: using-the-order-book.md
      - How to Earn Profits: how-to-earn-profits.md
  - Private Market:
      - User Private Market: user-private-market.md
      - Merchant Private Market: merchant-private-market.md   
  - Dispute resolution process: dispute-resolution-process.md      
  - Merchant platform:
      - How to Integrate Dapp?: how-to-integrate-dapp.md
      - Merchant Center: merchant-center.md
  - Developer Resources:
      - Open API: open-api.md
  - FAQs:
      - Overview: faqs.md
      - Can I Sell Early?: can-i-sell-early.md
      - How Do I Contact Support?: how-do-i-contact-support.md
      - Is My Money Safe?: is-my-money-safe.md
      - Why Crypto?: why-crypto.md
      - What is a Prediction Market?: what-is-a-prediction-market.md
